"""Add fixed_expenses and fixed_expense_records tables

Revision ID: 0e40f1686bf7
Revises: 15ba7ab62cc0
Create Date: 2025-10-23 09:50:35.485401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e40f1686bf7'
down_revision: Union[str, None] = '15ba7ab62cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_amount', sa.Integer(), nullable=True),
    sa.Column('is_fixed_amount', sa.Boolean(), nullable=True),
    sa.Column('expected_payment_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_expenses_id'), 'fixed_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_fixed_expenses_user_id'), 'fixed_expenses', ['user_id'], unique=False)
    op.create_table('fixed_expense_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed_expense_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fixed_expense_id'], ['fixed_expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixed_expense_id', 'year', 'month', name='unique_year_month_per_expense')
    )
    op.create_index(op.f('ix_fixed_expense_records_id'), 'fixed_expense_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixed_expense_records_id'), table_name='fixed_expense_records')
    op.drop_table('fixed_expense_records')
    op.drop_index(op.f('ix_fixed_expenses_user_id'), table_name='fixed_expenses')
    op.drop_index(op.f('ix_fixed_expenses_id'), table_name='fixed_expenses')
    op.drop_table('fixed_expenses')
    # ### end Alembic commands ###
