"""Add valid_from and valid_until to fixed_expenses

Revision ID: b9efa9c9af0e
Revises: 0e40f1686bf7
Create Date: 2025-10-23 10:11:15.397296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9efa9c9af0e'
down_revision: Union[str, None] = '0e40f1686bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_expenses', sa.Column('valid_from', sa.Date(), server_default=sa.text('(CURDATE())'), nullable=False))
    op.add_column('fixed_expenses', sa.Column('valid_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_expenses', 'valid_until')
    op.drop_column('fixed_expenses', 'valid_from')
    # ### end Alembic commands ###
